### ISSUE TITLE
LU product tables 

### ISSUE THREAD

**Issue by k2viewRami** [k2view-academy/K2View-Academy#1005]
what is the use of these tables and what type of information will be stored there.

_k2_delta_errors     
_k2_read_pos         
_k2_transactions_info

**Comment by eyalk2** [comment]
Hi
you can read about these tables [here](https://support.k2view.com/Academy/articles/13_LUDB_viewer_and_studio_debug_capabilities/01_data_viewer.html)

* k2_delta_errors - The delta failed transactions are reported to this table
* k2_read_pos - for common only; stores offset in Kafka; it is required to allow common backup. To see status - instead of looking at this table - run ref_status command
* k2_transactions_info - contains information about each transaction

**Comment by ShaniRotemIl** [comment]
Hi,

1. If _k2_read_pos is only for Commons, why do we see it in each LUI?
2. _k2_transactions_info is about iidfinder delta trx? or also for Common tables only?

Thanks

**Comment by natalylic** [comment]
**_k2_read_pos** is a Common only table, and it shows the last PubSub position that was processed by Fabric on each table. You can see it in each LUI because the Common schema is always there.
**_k2_transactions_info** is not in use. It was used by CDC zombie transactions prior to 7.1 (7.2) version.

**Comment by natalylic** [comment]
After additional investigation, the tables **_k2_read_pos** and **_k2_transactions_info** will be removed from the LUI schema (in the next Fabric version)
