### ISSUE TITLE
SSO auto logoff timeout configuration

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1013]
Hello, our client is asking if there is a way to configure timeout for SSO authentication, so users will be logged-off automatically after some inactivity period.

Could you please share 
* for WebStudio - what is default timeout and what is the process to change it if needed?
* for Fabric / TDM Admin UI via SSO/SAML (when Fabric is running w/o cloud or on-prem K8s, no CyberArk) - is there any configuration on Fabric side for that SSO log-off timeout as well?

______________
Best regards,
         Andrey

**Comment by eyalk2** [comment]
- In general, Fabric provides JWT based auth - serverless session management. Session timeout is configured at config.in (WEB_SESSION_EXPIRATION_TIME_OUT). User access is extending this. For example, if it is set for 15 minutes and user accesses after 10 minutes since session started, then he will have another 15 minutes, from that point.
- For Web Studio it is set to be 540 minutes = 9 hours - assumed as working day.
- When SSO/SAML is configured, then the external IDP manage it. Yet, as long as session at Fabric is not ended, then it would not go out into the IDP. As explained, Fabric sessions is extended by user access. To limit it, you can use another config.ini parameter - WEB_SESSION_MAX_DURATION. This limits the overall time of a user session in Fabric. To be effective, it shall be less than the session max time which defined at the external IDP.

**Comment by avvakandr** [comment]
Hi Eyal, for WebStudio with SSO/SAML - is it something we can adjust for customer, if they want this timeout to be less than 9 hours? If SSO enabled for WebStudio - is it some CyberArk config or still it is customer IDP behind the scene?

**Comment by eyalk2** [comment]
yes, you can change the default of 9 hours in the project space profile. as explained at https://github.com/k2view-academy/K2View-Academy/issues/1012.
for SSO - can be configured the same way. having CyberArk with minimal session time, it will be directed to the IDP
