### ISSUE TITLE
Broadway Flow Input Parameter naming convention

### ISSUE THREAD

**Issue by debargha95** [k2view-academy/K2View-Academy#1021]
Hi,

I noticed that certain variable names are reserved and can't be used as broadway input parameter names like case, table, index etc. They work when we run in the flow 
![image](https://github.com/k2view-academy/K2View-Academy/assets/165196534/3fac3288-8781-40e5-b00b-416b64aeab7d)
but when we run via the console they throw an exception. We have to wrap it around '' for it to work. 
![image](https://github.com/k2view-academy/K2View-Academy/assets/165196534/472cb20c-5864-4ca2-80a9-6a35e7ea8877)

Do we have a list of reserved keywords for broadway input parameters anywhere on the support page?
Is it the sqllite list of reserved keywords? 
Can we have this information added to the Best Practices for Broadway?

Thank you.

Regards,
Debargha Ghosh

**Comment by natalylic** [comment]
The reserved keywords are not specific for Broadway, but rather for Fabric in general. 
Most of them are standard SQL & SQLite reserved keywords.

**Comment by debargha95** [comment]
I understand. Can you please add to the support page the list of such keywords if it is not already there?

**Comment by natalylic** [comment]
We would rather don't upload the list of keywords to the Support, since this list is dynamic. So in case of adding a new word, we wouldn't want to have an outdated list in our Knowledge base. 
Instead, the troubleshooting of this problem is: when running a fabric command and the exception "Encountered..." is thrown, you need to check the command syntax. One of the reasons for the exception is a usage of the reserved word which is solved by adding the quotes.
