### ISSUE TITLE
Fabric Studio Web - How to enable browsing Open VSX registry from the Extensions panel

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1086]
Fabric Studio Web 7.2.2

On the Extensions panel there is an option to enable view of extensions installed from Open VSX.
I assume that it will show extensions that were installed using the extension's VSIX file.
How to enable browsing and search on the Open VSX registry, from the Studio itself?

Also, is it possible to install extensions from Visual Code Marketplace?

Please advise.
Thanks.

**Comment by feamcor** [comment]
I managed to install extensions from the Visual Studio Code Marketplace.
Anyway, it was an offline installation (i.e., download VSIX to local machine, upload it to Space, and install it from the Extensions panel).
So, another question that arises is where should be the best place to upload the VSIX files?

**Comment by eyalk2** [comment]
Open VSX as its name, is an opened place, not under the terms, regulations, ownership and propriety rules of Microsoft.
Originally it is aimed for VS Code users. In many cases, developers upload their stuff in both places.
Open VSX was initiated by Eclipse foundation which also found and promote Theia, which is an extensible and open IDE, following VS Code. Theia shows Open-VSX in its Extension View, same as VS Code shows the MS marketplace. Nevertheless, not all Open VSX extensions fit and compatible to Theia, as there are gaps between them. Having said that, in latest Theia versions such gaps are mostly closed and they try not follow VS Code changes and avoid gaps.
Web Studio is based on Theia, so the things above are relevant to it too.

Since we created K2exchange, which is K2 open-vsx based deployment, we hide the default Open-VSX, mainly to avoid confusions,
You can reveal it via settings > Extensions: Enable Search - tick the checkbox. Then you can see and search Open-VSX. Of course your Studio need to be opened to the internet.

I'm not sure if you can or want to see K2Exchaneg right now

**Comment by feamcor** [comment]
I enabled the search and it is working. Thanks Eyal.
