### ISSUE TITLE
IIDFinder - k_<lut>_iid_info table - cause

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#1104]
Fabric 6.5.9

When IIDFinder identifies a delete transaction to the root table, it inserts and entry on the IID Info table, but column `cause` is set as `null`. Because this column is `null` it seems that IID Finder library doesn't ignore further transactions that arrive to the relevant IID. When `cause` is populated, then it does.

How is the `cause` column used by IID Finder?
Who is supposed to populate it?

Please advise.
Thanks.

**Comment by lionbro1** [comment]
Hi,
 
The iid_info table is filled by Fabric if instance is deleted by Fabric command and by implementation for other cases.

The possible values are:
delete – instance deleted by delete instance command – it will not receive updates from IidFinder, unless set SEND_TO_DELTA_IF_DELETED=true – inserted by Fabric
priority – instance is processed in separate delta topic – inserted by implementation
<empty sting> or <null> - regular instance
<non empty string> - Exclusion cause, the instance update will not be sent to delta by IidFinder – inserted by implementation
 
 
The described behavior (messages to deleted instance keep arriving) is defined by implementation, because in the same way it was deleted it can be inserted again.
