### ISSUE TITLE
How to deploy multiple LUs with one click/one command to remote fabric?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1111]
Hello, one of our TDM customers has lots of LUs (30+) and as part of their workflow they want to deploy all LUs to remote execution server from time to time with one click / script (doing it one by one is time consuming)... 

As I know our current build / deploy scripts (and deploy API) working for single LU only - is there a way to extend that script so we can supply list of LUs as input? Or maybe there is other way around to do so...

______________
Best regards,
          Andrey

**Comment by lionbro1** [comment]
Hi,

The deployment API works in LU level as mentioned above, in order to automate the deployment of 30 LUs our recommandation is to create a Broadway flow that will run the list command in order to get the list of all the LUs and use a loop within Broadway that will call the deployment API for each LU.

The execution of the Broadway flow can be trigger by a BroadwayJob or by calling fabric-command built-in product API.
