### ISSUE TITLE
Force upgrade after deploy and decision functions

### ISSUE THREAD

**Issue by ShaniRotemIl** [k2view-academy/K2View-Academy#1134]
Hi,

Referring to ticket https://k2view.freshdesk.com/a/tickets/10082

![image](https://github.com/user-attachments/assets/0a5313a7-352b-4381-8e5b-10a9b0af0435)

I'm trying to understand what is the reasoning behind it - why to ignore decision functions after deploy if even sync FORCE is not ignoring them?

Thanks

**Comment by lionbro1** [comment]
Hi,

This is the expected behavior, as this parameter impacts only the first LUI sync process. you can read more on the following article https://support.k2view.com/Academy/articles/14_sync_LU_instance/02_sync_modes.html under "Fabric Studio Server Configuration - Force Upgrade Post Deploy Checkbox" section
