### ISSUE TITLE
Masking cache concurrency control

### ISSUE THREAD

**Issue by gtoumiek2** [k2view-academy/K2View-Academy#1147]
in context of Masking
In case of multiple flows running in parallel (read/write operations) with to same Masking_ID, 

do we have any concurrency control?

for example, when masking a Name, while one flow is writing data to cache, and another tries to read the cache for same value, not finding it, eventually both generating their own masked values for that input, and both try to insert it to the cache

**Comment by taliei** [comment]
Hi.

In the case of concurrent processes that mask the same original value - for example: 2 processes try to mask 'John' - the 1st process generates a new value ('Ron' for example) and inserts it into the caching table. If the 2nd process tries to generate its own masked value, the insert into the caching table fails due to a violation of a unique key and the 2nd process re-tries to get the masked value (generated by the 1st one) from the caching table.

Tali
