### ISSUE TITLE
Web Service input with no field name in JSON

### ISSUE THREAD

**Issue by benkipnis** [k2view-academy/K2View-Academy#115]
I am trying to process a web service input (POST) that is a direct JSON array like:

```
{
[
{...},
{...}
]
}
```

The lack of a 'field name' at the front of the array seems to pose a problem for ingestion, as our standard web services expect something more like:

```
{
"array": [
{...},
{...}
]
}
```

How do i configure a web service to accept a direct array?  I've tried leveraging the request() object but am having trouble, so guidance is appreciated.

Thanks!

**Comment by lionbro1** [comment]
There are two  steps to be followed

1. request should have a header of content-type different from application/json

2. API should not contain input parameters and inside the API logic use this line in order to convert it to the structure you are looking for List<Object> list = Json.get().fromJson(request().getInputStream(), List.class);
