### ISSUE TITLE
Can Broadway flow be converted to JSON if developed on Fabric 8.x

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#1194]
I would like to export a logical unit that was developed in Web-studio with Fabric 8.0 and import it to Web-studio with version 7.2.
What would be the best way to achieve that?

**Comment by natalylic** [comment]
The flow format is controlled by the hidden parameter `BROADWAY_FILE_FORMAT `in the [broadway] section of the config.ini.
By adding this parameter to the config.ini and setting its value to `json`, the flows will be saved in JSON format.
In order to make it effective on the existing flows, open each flow and save it. Then it will be transformed to JSON format.

**Comment by alexmessel** [comment]
Nataly, the question is slightly different. 
Is there a way to convert a BW flow developed in 8.1.1 and saved as YAML to a JSON format so it can be used in earlier fabric versions that don't support YAML format for BW flow?

**Comment by natalylic** [comment]
Once the flows are converted back to JSON format (using the above parameter - as per my previous explanation), they can be used in earlier Fabric version.
