### ISSUE TITLE
Executing in Fabric Broadway Flows in shared

### ISSUE THREAD

**Issue by barakgk2view** [k2view-academy/K2View-Academy#120]
I have created in the Shared objects a few Broadway Flows, how can they be executed in Fabric as the execution command requires an LU?
 broadway <LUT>.<FLOW_NAME> [param1=value1, param2=value2...]
or 
startjob BROADWAY_JOB NAME='<lu_name.flow_name>' [UID='<uid>'] [AFFINITY='<affinity>'] [ARGS='<args>'] [EXEC_INTERVAL='<execInterval>'];

**Comment by lionbro1** [comment]
In order to run a broadway command on a broadway flow that is defined on the shared level, it is a must to deploy as least one LU (as it is inheriting the shared level flows) and run it accordingly.

For example if your shared level broadway flow is called MyBroadway and you deployed LU called Test, you can run it by

broadway Test.MyBroadway;
