### ISSUE TITLE
using Batch mode insert using DBLoad actor with MySQL DB

### ISSUE THREAD

**Issue by amirgk2view** [k2view-academy/K2View-Academy#1213]
Hi , 
I need to load (as part of TDM table level task) to  MySql table ,  source table consisting of 42M records. 

using the DBLoad actor , with batch set to true, performance is ~10k records per minute , which means that for the entire 42M records, it would take ~70 hours to finish. 

My question is if the DBload batch option in MySQL does utilize the driver batch insert option ( probably by using  INSERT INTO table (col1...coln) VALUES (val1...valn), (val1...valn)....(val1...valn); ) 

If not, how can I improve performance  ?

customer is using the following driver jar : mysql-connector-j-8.0.31.jar

addition : same question for Oracle (customer has large tables in Oracle as well)

**Comment by natalylic** [comment]
Is there a way to split the 42M records into groups, so that you can run the load in parallel?
If you can split them, you can use the **Parallel Execution** option in Broadway - as explained [here](https://support.k2view.com/Academy/articles/19_Broadway/30_support_parallel_execution.html).
Moreover, in the Fabric V8.2 (coming out soon) there is a new actor **InnerFlowSession** which opens a new session, so the parallel run can include separate transactions definition.

**Comment by natalylic** [comment]
The **DbLoad** actor is using a standard JDBC interface for batch load. It has no specific implementation per each DB type.
