### ISSUE TITLE
Where do I find xmls in server? 

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#122]
I am trying to find translation tables deployed into the server, checked in ludb.jar but didn't find.
also not finding ludbXMLs file.`

fabric version 6.1.6

**Comment by lionbro1** [comment]
Hi,

In order to know the details of the project deployed into a given environment, you can run the following URL from your browser

http://<ip address>:3213/lut?lutName=<lu name>&token=<token name>

For Example: http://localhost:3213/lut?luName=CRM&token=ABC

it will download the project to your laptop/PC.

Afterwards you can view the downloaded project on your Studio.

Same can be done for WSs and Ref

http://<host>:3213/lut?lutName=k2_ws&token=<token>
http://<host>:3213/lut?lutName=k2_ref&token=<token>
