### ISSUE TITLE
[TDM] TableLevel task - is there a way to assign custom extract/load flow to all tables except for few?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#1227]
Hello, one of our customers using TableLevel task to move 400+ tables from prod to test DB, and for efficiency / better performance we created custom flow that is utilizing SqlServer Bulk Load API and we set it in TableLevelDefinitions MTable for our interface and schema as a custom load flow... 

This is working fine for most of the tables, but for a few tables we hit known limitation for this bulk load feature (when specific datatypes can not be supported / copied ) and for these tables we would like to fallback to our default TableLevel load flows. 

Is there a way to configure TableLevelDefinitions in such a way that it will use my custom load flow for all tables, except for few that I list explicitly ? I currently made it working by using default flow names from Table Level LU as my custom flows for extract and load, but maybe there is another way:

![image](https://github.com/user-attachments/assets/ed59ff3b-4628-4419-a469-edc9cd883736)

_____________
Best regards,
         Andrey

**Comment by taliei** [comment]
Hi.

To exclude specific tables from custom flows and apply generic logic instead, populate the TableLevelDefinitions MTable with the GetSourceDataByQuery and LoadTableByQuery flows for those tables as shown in your screenshot. This configuration ensures that the selected tables will use the standard processing approach rather than any custom-defined workflows.

Regards,
Tali
