### ISSUE TITLE
List of all SQLs fabric executes during GET

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#123]
In Fabric, is there a way to retrieve all the sql queries along with the WHERE clauses that are being used from the LU?

**Comment by lionbro1** [comment]
You can use the trace command for this purpose. Since fabric 6.2.0 it is supported also on the session level.

Example of opening a trace on a session level to monitor 2 get commands and turning the trace off afterwards.​

trace session_scope example1 'categories=solutions;operations=sync;'​

get Customer.1;​

get Customer.2;​

trace off;​

A file is generated under /k2view/home/traces/ or <Projects path\Projects\<project name>\FabricHome\traces​

To view the file content, use http://<ip>:3213/static/trace/trace.html​
