### ISSUE TITLE
trying to call another lu in enrichment and getting error

### ISSUE THREAD

**Issue by tamarzohar** [k2view-academy/K2View-Academy#144]
My code is in enrichment function from price plan lu and I’m doing get in this enrichment for another lu .
The enrichment code is : 

try
{
            // Fetch All Price Plan's Related SOCs from SOC_RELATED
            Db.Rows rows = ludb().fetch(socList_SQL);
            for (Db.Row row:rows) {
                        String soc = (String)row.cell(0);
            
                        reportUserMessage(Level.INFO, "SOC = " + soc + "SOC Length = " + soc.length());
              DBExecute("dbFabric", "get SOC.'" + soc + "'", null);
                        Fubric().execute(“get SOC,?”,soc);
/// calling template 

}

dbFabric – is the remote fabric interface 

when changing it to :  Fubric().execute(“get SOC,?”,soc); I’m getting error : 

ERROR 2020-11-22 11:41:48,124 [LID1a8c000000000037] [JdbcEx Server-5/127.0.0.1:65268] c.k.c.s.u.UserCode - Error in PRICE_PLAN sub Jsons Handling: 'SOC' can't be detached while in transaction

please explain why

**Comment by lionbro1** [comment]
Hi,

You are getting this error message, because somewhere in the code you have another get for SOC or Price plan LU and it can’t detach an instance in the middle of a transaction.

You have two options:

1.	Find out where is the other get and put it in comment if possible.
2.	Open another fabric local session instead of using Fabric remote

For example :
openFabricSession(“fabric2”);
db(“fabric2”).execute(“get SOC.?”,soc);
