### ISSUE TITLE
Parsers vs Broadway flow 

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#155]
Hi,

Are there any performance improvements or any other significant improvements in using Broadway flows to perform activities that the current Fabric parser performs like dumping data from source to Cassandra?
Also, there is a configuration section specific to parsers in config.ini which can be tuned for optimal performance. Do we have something similar for Broadway?

Thank you,
Hardik

**Comment by natalylic** [comment]
The product recommendation is to use Broadway flows rather than parsers since Broadway flows are more flexible and their maintenance is more simple (most parser's code is replaced by the Actor's functionality). To load data to Cassandra table by Broadway you can use the [Cassandra loader](https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.2/articles/28_cassandra_loader/README.md) which is also used by the parsers. The related configuration in config.ini remains the same. The performance of both processes is similar.
