### ISSUE TITLE
Change MDB_DEFAULT_CACHE_PATH per LUT

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#196]
Config.ini allows us to define for Fabric the base path for storing MDB files: MDB_DEFAULT_CACHE_PATH

Can different LUTs use different values? Such that one LUT uses memory (/dev/shm/fdb_cache) and another LUT uses a disk volume?

Desire is to allow small LUTs to leverage memory, but also support on the same cluster a few large LUIs which may exceed free memory. For those LUT with larger instances, instead use disk space and accept the difference in IOPS performance.

**Comment by feamcor** [comment]
It should be possible and it seems that they try to explain it [here](https://github.com/k2view-academy/K2View-Academy/blob/d79eeaa468b179b8e649b135643e372902beff33/articles/32_LU_storage/02_storage_management.md), but I didn't understand how.

**Comment by natalylic** [comment]
Fabric enables to modify the default location of the cache **per Logical Unit** using the LU Schema's **Cache Location** property:
![image](https://user-images.githubusercontent.com/62207927/111068223-97379b80-84d0-11eb-94b6-d4d12ee29328.png)
Please refer to the sub-chapter "Changing the Location of the Cache" of the following article:
https://support.k2view.com/Academy_6.4/articles/32_LU_storage/02_storage_management.html
Please note that if you update the **config.ini** setting from the default value to another location, it will be considered by Fabric rather than the LU Schema's **Cache Location** property.
