### ISSUE TITLE
Consistency level used by Fabric when writing an entry to k2_jobs table

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#197]
What is the consistency level used by Fabric when writing an entry to k2_jobs table? We are seeing below error when deploying reference tables.

> Caused by: com.k2view.cdbms.exceptions.JobException: Error while Adding new record to k2_jobs
> Caused by: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during CAS write query at consistency SERIAL (5 replica were required but only 0 acknowledged the write)

The consistency level set in config.ini in all fabric nodes is LOCAL_QUOROM
> CASSANDRA_CONSISTENCY_LEVEL=LOCAL_QUORUM

Thanks,
Hardik

**Comment by smokyMount** [comment]
Found this from the wiki below page:
https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/02_fabric_architecture/05_fabric_main_configuration_files.md

> SERIAL_CONSISTENCY_LEVEL, default is LOCAL_SERIAL. Used internally for Fabric Jobs.

But why is it failing to write to k2_jobs table with the error posted in the issue when all 9 nodes are up while it only requires 5 nodes to be up for consistency SERIAL?

**Comment by greg-k2view** [comment]
How many jobs were not written in the jobs table ?  - and  could we get timestamps of the successes/failures for these jobs entries, as well as the jobs affinity ?

**Comment by greg-k2view** [comment]
indeed SERIAL_CONSISTENCY_LEVEL (default is LOCAL_SERIAL) is the parameter to configure as it is used in the ref tables synchronization process. 
We will need also to know what was the status of the cassandra servers (logs) - it is not because all all 9 nodes were up that there was no issue at the same time.
I am closing this issue here as the best way forward is to open a support ticket in freshdesk with the info & logs of the incident. Please tag me there as well.
