### ISSUE TITLE
is it possible to skip failure in DBQueries ?

### ISSUE THREAD

**Issue by tarikhad** [k2view-academy/K2View-Academy#199]
For example if during executing DBQuery one record has PK as null, is there away to make population skip this record or yield whatever was fetched and move on?

**Comment by taliei** [comment]
Hi.

First, it is recommended to use fetch() method instead of DBQuery, since DBQuery is deprecated. See details in the following article: 
https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/05_DB_interfaces/09_fabric_API_for_DB_interfaces.md

To your question- 
You can wrap the call to the DBQuery or fetch methods by try and catch in your code to handle exceptions.

**Comment by tarikhad** [comment]
Hi,

with DBQuery I meant using Query Builder and not using a root function.

**Comment by taliei** [comment]
Hi.

There are 2 ways to add error handling to an LU table population:

1. Using a root function
2. Using a Broadway flow to populate the LU table and add the ErrorHandler actor to the flow.

See instructions on how to build a table population using Broadway flow and use the ErrorHandler Actor in the following URLs:
https://github.com/k2view-academy/K2View-Academy/blob/Academy_6.4/articles/07_table_population/14_table_population_based_Broadway.md

https://github.com/k2view-academy/K2View-
Academy/blob/Academy_6.4/articles/19_Broadway/actors/06_error_handling_actors.md#how-do-i-use-the-errorhandler-actor
