### ISSUE TITLE
Fabric - How to generate logs in JSON format

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#209]
Hi,

Is there a way to generate logs (inside k2fabric.log file) in JSON format?

Thanks,
Hardik

**Comment by lionbro1** [comment]
Hi Hardik,

Not sure what is the reason for this request, what is the business case?

Are you looking only for error logs? as you can use ErrorHandler Actor to catch the errors.

But it will not cover all log messages, as it's not in standard format.

Need better understanding on the business requirement before advising how to move forward.

**Comment by smokyMount** [comment]
The customer needs to feed the logs to Kibana for generating alerts and monitoring. They said it has to be in json format for Kibana to read the logs.

**Comment by lionbro1** [comment]
Hi,

This is not correct, you need to use filebeat or logstash agents in order to stream our logs to a a format that Kibana can interact with.

**Comment by danicar12** [comment]
That’s correct, in other projects we are using filebeat to feed kibana.

Thanks,
Daniel

On 12 Apr 2021, at 08:24, lionbro1 ***@***.***> wrote:

﻿

Hi,

This is not correct, you need to use filebeat or logstash agents in order to stream our logs to a a format that Kibana can interact with.

**Comment by JohnH-K2View** [comment]
Hi Daniel,

Do we have any implementation guide or best practices for fabric / filebeat / logstash?

**Comment by danicar12** [comment]
Hi John,

It was managed by the customer so not really a guide.
What I can share is that they install filebeat on every fabric node so that it will be collecting regularly the log information.
In the end this information is being presented in Kibana graph.

Best regards,

[Icon  Description automatically generated]<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.k2view.com%2F&data=04%7C01%7Cdaniel.carrera.alonso%40k2view.com%7Ca743acd3e5be4eb0a86b08d8ea2d3dbd%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C637516827370541265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qDuNMcEYynMI5L2Id1tAtQwjHb3WhcqUPGfOXL1eCUA%3D&reserved=0>
Daniel Carrera Alonso
Technical Account Manager (EU)
Mobile: +31 (0) 629395413



From: JohnH-K2View ***@***.***>
Date: Tuesday, July 6, 2021 at 10:31 PM
To: k2view-academy/K2View-Academy ***@***.***>
Cc: Daniel Carrera Alonso ***@***.***>, Comment ***@***.***>
Subject: Re: [k2view-academy/K2View-Academy] Fabric - How to generate logs in JSON format (#209)

Hi Daniel,

Do we have any implementation guide or best practices for fabric / filebeat / logstash?

**Comment by gabiochman** [comment]
Hi John 

bellow is example for filebeat.yml

<img width="496" alt="Screen Shot 2021-06-22 at 16 00 45" src="https://user-images.githubusercontent.com/17381797/124724383-9fe72e00-df14-11eb-9e35-97951c6dad0c.png">

**Comment by gabiochman** [comment]
see example bellow for **filebeat.yml**

<img width="606" alt="Screen Shot 2021-07-07 at 11 14 54 AM" src="https://user-images.githubusercontent.com/17381797/124724553-c1e0b080-df14-11eb-9186-4f31664d8082.png">

**Comment by JohnH-K2View** [comment]
Updated request from Verizon, they're requesting this for some other log ingestion as well. They're requesting this as a company wide standard for log formats; so their log management can be common across applications.

**Comment by smokyMount** [comment]
Do we have any info on the config needed to use logstash?

**Comment by gabiochman** [comment]
Hardik

the **logstash** is part of the **ELK stack**,  the customer have to install it and configure it. it is not in the K2view domain .

the **filebeat** is the agent that should run on the F* / C* / K* nodes and push the data to logstash.

let me know we  need to schedule teams session
