### ISSUE TITLE
access config.ini params via code

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#23]
Is there a way to access config.ini params via code?
 
The same way iifConfig.ini is accessable through IifProperties.
 
I looked into properties classes but couldn’t find.

**Comment by lionbro1** [comment]
Hi,

Need to understand better what is the exact use case. You can't access the parameters via code due to the following reasons:

1. We should avoid backward compatibility issues, as name of parameters can be changed/added/removed.
2. Parameters are used internally by the product.
3. If a user should have the ability to change a given parameter, you have a dedicated command for it (for example set sync_timeout).

**Comment by tarikh03** [comment]
Hi,

In code we will be using KafkaConsumer which will listen to the kafka servers defined in config.ini under BOOTSTRAP_SERVERS.

In order for that to be generic code for all environments we need to get this parameter.

**Comment by lionbro1** [comment]
In this case you can define the kafka interface and override it using the environment functionality and use the interface properties according to the environment you use.
