### ISSUE TITLE
sync on and get is a must in DBQuery using fabric DB.

### ISSUE THREAD

**Issue by tarikhad** [k2view-academy/K2View-Academy#244]
DBQuery based on fabric db cannot be saved without having Pre-execution commands set sync on and get LU.IID.

Why do we need to have those commands as mandatory in DBQuery selecting from LUI db in context?

while in root function we can still have same query with sync on and get.

steps to reproduce:

1. have an LU with table X and Y
2. create a population for table Y and use DBQuery, set interface to fabric.
3. "Enable Pre-Execution Commands" check box is checked by default with commands set sync on and get <LU>.IID,
     if unchecked, DBQuery won't be able to save.
4. expected is to have the option to rely on query and just select from fabric db in context without executing Pre-Execution Commands.

**Comment by natalylic** [comment]
The context of your question is not clear. See below the population which is based on DBQuery from fabric DB. When running it in debug mode, I'm not requested to execute pre-execution commands since the IID is provided in the Instance field.
"Enable pre-execution commands" is the mandatory option of the Query Builder, since this is how you provide the IID when running the Query Builder.
![image](https://user-images.githubusercontent.com/62207927/116815420-2b83bd80-ab66-11eb-88b3-5eeda46c131f.png)
