### ISSUE TITLE
How to Build JSON Object/Document in Broadway

### ISSUE THREAD

**Issue by mpp4manu** [k2view-academy/K2View-Academy#256]
We need to build a flow that does the following:

1. Subscribes to a Kafka topic
2. Parses out a single value
3. Creates a JSON Object (payload) that will include a large number of static objects and will have nesting
4. Send the payload to a REST API

What is the best way to create the JSON document in Broadway?  I'm hoping there's something like Freemarker templates or schema that allow for variable substitution.

**Comment by natalylic** [comment]
The following actors are available in Broadway:
**JsonParser** - A JSON parser, analyzing an input stream and outputting the JSON objects found in the stream.
**JsonStringify** - Serializes an Object into JSON.
**Http** - Send a request to a web server. Supports streaming payload and result and sending and receiving header parameters.
**HttpJson** - Send a request to a web server stringifying the request into JSON and parsing the JSON result. In case of a JSON parsing error, the actor will throw an exception.
What kind of variable substitution do you need to perform? Please elaborate and provide an example.

**Comment by natalylic** [comment]
You can also use **JavaScript** actor in order to modify the JSON prepared by the **JsonParser** actor.
In addition, **Graphit** utility is available in Fabric to enable the creation of dynamic JSON documents.
https://support.k2view.com/Academy_6.4/articles/15_web_services_and_graphit/17_Graphit/01_graphit_overview.html
Once created, you can invoke it using the **Graphit** actor.
