### ISSUE TITLE
Broadway Actor EXEC

### ISSUE THREAD

**Issue by tonysemaan307** [k2view-academy/K2View-Academy#279]
I tried to run this command using Broadway actor exec
chmod +766 <folder_path> 
and I had some issues, at the end it works.

actor's inputs : 
command = chmod
params[] = 2 param : 
1. 766 (without +) 
2. <folder_path>

* make sure there is no spaces in the parameters

**Comment by natalylic** [comment]
This is correct. Also note that if you need to use the external parameter(s) in the flow rather than setting a "hard-coded" value, you can create the params array using the **ArrayConcat** actor and then pass it as an input to the **Exec** actor, as shown below:
![image](https://user-images.githubusercontent.com/62207927/122745600-d88ad480-d291-11eb-8d5b-294f6ce8ecf1.png)
