### ISSUE TITLE
Reaper Repair Scheduling

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#292]
Is it safe to run a keyspace repair from reaper on any keyspace at any time? Or should it be only run during Cassandra's idle time?

**Comment by gabiochman** [comment]
It is recommended to:

- schedule it for non-pick hours
- On big C* clustrer, split the jobs to run per tables
- Don’t run repair job cross DC’s, only if it is monitored 
- Don’t run repair jobs during high compaction time, Cassandra-reaper is pausing the job in case of more then 20 pending tasks
- Run the first Cassandra-reaper jobs manually in order to see how long it takes and base on it schedule it
