### ISSUE TITLE
Broadway - DateParse behavior

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#294]
Hi,

I am using a DateParse actor to convert a String (eg: 2020-03-12) to Date format which is then later inserted into a Date datatype column in Cassandra table. 

The Input is 2020-03-12
The format in DateParse actor is yyyy-MM-dd. 
The output is 2020-03-12 00:00:00

As shown in the image, the DateParse actor is adding timestamp to the date, which in turn throws error when we try to insert into Cassandra table. Is this an expected behavior from DateParse actor?

![image](https://user-images.githubusercontent.com/66338066/125635622-7a0945bb-3a5d-4909-8bd7-df122f432dbb.png)

**Comment by smokyMount** [comment]
Just to add that this behavior was found in v6.4.2.

**Comment by natalylic** [comment]
The **DateParse** actor returns a **date** object. A date object is a point in time regardless of how you parse it. 
You can use the **DateFormat** actor to get rid of the timestamp.
In any case, we are planning to handle the conflict of date vs datetime types in Cassandra in the future versions.

**Comment by smokyMount** [comment]
Thanks, Nataly! By using the DateFormat actor, the date is converting back to String datatype which is not getting inserted to the Cassandra table as the datatype of the column is **date**.  Is there another way to fix it?

**Comment by lionbro1** [comment]
Cassandra is using a custom date object type.
In 6.5.2, we will add a codec that will convert it to java Date.
As a WA (since String is not working) create an LU function that will do the conversion to the standard Cassandra date type.
You can use a long in Cassandra instead of Date.

p.s. please re-evaluate the fact that string doesn't work, because according to Cassandra KB:

Value is a date with no corresponding time value; Cassandra encodes date as a 32-bit integer representing days since epoch (January 1, 1970). Dates can be represented in queries and inserts as a string, such as 2015-05-03 (yyyy-mm-dd)

**Comment by smokyMount** [comment]
Unfortunately, the datatype cannot be changed on the Cassandra table. As a workaround, we are building the insert statement outside of DbCommand actor and then pass it as an argument.
