### ISSUE TITLE
Acknowledged common table update

### ISSUE THREAD

**Issue by IvanKostyuk** [k2view-academy/K2View-Academy#307]
While maintaining reference data via webservices, I need a reliable way to know, that another webservice, which can be called by the same client right after updating one, can get just populated values.

Insert happens in transaction into 4 reference tables. Then commit. After commit, REF_SYNC_WAIT is called (according to documentation Wait for list of tables to be synced or transaction to completed on the session till a pre-defined timeout. Should run ... after insert/delete/update on common table).
However. very often  consequent service does not get data from one or more tables.

What should be done, to wait until update is completed in common tables?

**Comment by greg-k2view** [comment]
It is not currently possible for another webservice to know the status of the reference tables synchronization initiated by a different web-service (asynchronous). in addition , it might be that the reference table synchronization is happening across multiple nodes which makes it difficult to "predict" when the synchronization process of copies of the tables (one per node) will be over.

Also the **ref_sync_wait** command cannot be invoked from the second webservice since it will be run in a different session than the one that initiated the reference table updates.

It looks like the appropriate orchestration of web-services should be dealt at project level as opposed to product level since the waiting factor is highly depending on the load  generated by the project implementor.
