### ISSUE TITLE
How to know which user deploying to fabric

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#312]
Hello,

In user preferences ,, by default we have the credentials required to deploy to fabric server. I would like to know if we store history of deployments to the server , with perhaps the username/Ip address of the user deploying to cluster.

Regards,
Prathamesh

**Comment by lionbro1** [comment]
Hi,

You need to turn the auditing mechanism on to get this info. since it can impact the performance of the system, you can filter the auditing to report only deploy activities.

Further info can be found on the following article:

https://support.k2view.com/Academy_6.5/articles/27_auditing/01_auditing_overview.html

If you wish to know only statistics, like how many times this LU was deployed, when it was deployed last time, etc.. (without specific user info), we have JMX matrics that expose it.
