### ISSUE TITLE
regional multi dc cluster

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#313]
Does order of IPs in config.ini#HOST guarantees first to be picked as a contact point?

for example:

1. there is 2 DC regional cluster, EAST DC and WEST DC.
2. fabric node is installed in EAST.
3. config.ini#HOSTS=<EAST IP1>,<EAST IP2>,<EAST IP3>,<WEST IP1>,<WEST IP2>,<WEST IP3>

having all the above, is it guaranteed that fabric will reach first to <EAST IP1> and most probably pick contact point in the EAST unless DC is down?
after contact point is picked, and if we are using LOCAL_QUORUM, then contacted point will reach only nodes in same DC?

Does the above sound like that way Fabric reaches out to cassandra?

**Comment by lionbro1** [comment]
Hi,

You need to define in the config.ini  HOSTS parameter only IPs from EAST DC, in order to guarantee that Fabric nodes will be marked as EAST DC related. Once Fabric made the connection to Cassandra the DC related to node's IP that established the connection will be consider as the local DC for LOCAL_QUORUM consideration.

Fabric will use the list of IPs according to the order defined on HOSTS parameter, it will pick up the IPs one by one till it will manage to establish a connection to Cassandra.

**Comment by tarikh03** [comment]
so if HOST were configure as below:

HOSTS=EAST IP1,EAST IP2,EAST IP3,WEST IP1,WEST IP2,WEST IP3

let us assume fabric established a connection successfully with EAST IP1, in that case there is no chance that fabric executes the actual query/command on WEST DC, even if we had WEST IPs in HOSTS?

is that right?

**Comment by lionbro1** [comment]
that is not correct, you must put only EAST IPs in HOSTs so when you run a fabric command on one of EAST IPs it will not use WEST nodes as you use LOCAL_QUORUM. you also need to make sure when you run jobs to put as affinity the EAST DC

**Comment by tarikh03** [comment]
just edited my comment as I saw some part disappeared. :)

Thanks Lion.
