### ISSUE TITLE
Changing fabric log time zone

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#33]
How to change fabric log time to a specific time zone?
How to change the fabric log to match the server time zone?

**Comment by natalylic** [comment]
Fabric log time is set according to the Fabric server time zone definition.
To set the Fabric server to a specific time zone, use the following commands:
1) To get a to list of time zones:
>timedatectl list-timezones
2) To set the time zone:
>timedatectl set-timezone <timezone>
Please note that you need to have root (admin) permissions in order to execute these commands.
