### ISSUE TITLE
Information regarding lrucachesize in masking actors

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#356]
Hello,

Our documentation only says that it will be the number of masked values stored in the local LRU cache. 
I would like to know , 1> if there has been any study regarding setting different values of lrucachesize as say 50,000 100,000. I am looking for performance impact numbers, if available.   
2> Suppose I have set lrucachesize as 1000 and the k2masking contains more than 100,000 values , is it Fabric itself that decides which values would be stored in lrucache or the user can define any logic to insert into cache ?

I would also like to know the different masking mechanism that we support, ( Link - https://support.k2view.com/Academy_6.5/articles/19_Broadway/actors/07_masking_and_sequence_actors.html ) According to the link we are supporting IN_MEMORY or SQL_DB as Cassandra(k2masking)  as masking cache. Is there a way that we can directly utilize fabricRedris as a maskingcache mechanism ? 
Regards,
Prathamesh

**Comment by taliei** [comment]
Hi.

lruChacheSize parameter:
This parameter is set to have a local caching of the masked value. This is usually used when getting the same values for masking by a loop. For example- parse and mask XML data. So - whenever having the name "Prath", the process can quickly get the masked value for "Prath" from the memory. Since this parameter is used locally- by an actor and node, its value is relatively small (1000). 
The LRU cache is a kind of Queue — if an element is re-accessed, it goes to the end of the eviction order. 
Whenever a new element is brought in, it is added at the head of the queue. When eviction happens, it happens from the tail of the queue. 

Please advise if you encounter any performance issues when running the masking actors.
 
Cache Storage:
Currently, we support in-memory or Cassandra for caching. The Redis is only used to get the next value.

Regards,
Tali
