### ISSUE TITLE
Create IntelliJ IDEA project without IDEA

### ISSUE THREAD

**Issue by IvanKostyuk** [k2view-academy/K2View-Academy#361]
I have native IntelliJ IDEA on MacOS while Studio (6.5.3) is running in Windows via Parallels. There is no IDEA on Windows. How can the IDEA project be created/refreshed with latests modules/LUTs and all libraries on:
- Windows from Studio without IDEA;
- On MacOS from command line?

**Comment by greg-k2view** [comment]
Hello Ivan, 
you need to run IntelliJ on the parallel where Fabric is installed - that is the best way to make the most of the tight integration between Fabric and intelliJ.

Since MacOS sees the files in the parallel, you should be able to see the Fabric project files residing in the parallel, but debugging and attaching a process would be challenging and is not currently supported !

**Comment by IvanKostyuk** [comment]
Thank you, Gregory.

I did it to create the project files. Then opened the project on MacOS updated the library paths (to orthodox paths). But when I opened the project in Studio, all the files were updated and my changes to the paths were gone.

I noticed, once IDEA is installed, Studio creates/updates .idea/ directory and files upon opening the project in Studio.

I'd like to disable automatic and have ability to trigger creation/update of .idea/ manually with and option to enhance and override.

I did not find how to block update of .idea/ in User Preferences.
