### ISSUE TITLE
View Translation data deployed on server

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#428]
Is it possible to view the data in translation tables that have been deployed to the server?  In studio we have this available, but once deployed can we validate the rows on translation tables, either through CLI or admin web portal?

**Comment by lionbro1** [comment]
Hi,

There is no Fabric command or sql statement that can bring you translation tables data, you need to use the APIs within the code as stated on the following article:

https://support.k2view.com/Academy_6.5/articles/09_translations/05_translations_code_examples.html

You can write a WS that will use these APIs in order to fulfil this requirement.

Regards,
Lion
