### ISSUE TITLE
Cases of Fabric allocating system memory (as reflected in pmap) rather than JVM

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#433]
In what instances could fabric (or possible implementation code) allocate system memory.  I know the MDB cache file can reside in /dev/shm/fdb_cache (default path); but we also see other instances of fabric allocating system memory.

At issue is USP production nodes gradually reserving more and more system memory outside of their JVM heap (beyond what's accounted for in /dev/shm).  This grows from ~25% of available memory right after "k2fabric start" to over 50% after 2 weeks of uptime.

Example form PMAP shows a gradually growing number of [ anon ] allocated memory blocks:

5831:   java -classpath :/opt/apps/k2view//config:/opt/apps/k2view/fabric/lib/fabric/*:/opt/apps/k2view/fabric/lib/provided/*:/opt/apps/k2view//ExternalJars/*:/opt/apps/k2view/fabric/resources -DFABRIC_HOME=/opt/apps/k2view/ -DPROCID=5831 -Doracle.jdbc.maxCachedBufferSize=16 -Doracle.jdbc.ReadTimeout=900000 -Doracle.jdbc.implicitStatementCacheSize=128 -Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl -Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerc
Address           Kbytes     RSS   Dirty Mode  Mapping
00000001c0000000 25190904 25161952 25161952 rw---   [ anon ]
00000007c187e000 1023496       0       0 -----   [ anon ]
000055a420d70000       4       4       0 r-x-- java
000055a420f70000       4       4       4 r---- java
000055a420f71000       4       4       4 rw--- java
000055a421123000 7039728 7039728 7039728 rw---   [ anon ]
00007fa7ec000000   29120   29120   29120 rw---   [ anon ]
00007fa7edc70000   36416       0       0 -----   [ anon ]
00007fa818000000   65536   65536   65536 rw---   [ anon ]
00007fa820000000  131072  131072  131072 rw---   [ anon ]
00007fa828000000  131072  131072  131072 rw---   [ anon ]
00007fa830000000  131072  131072  131072 rw---   [ anon ]
00007fa838000000  131072  131072  131072 rw---   [ anon ]
00007fa840000000  131072  131072  131072 rw---   [ anon ]
00007fa848000000  131072  131072  131072 rw---   [ anon ]
00007fa850000000  131072  131072  131072 rw---   [ anon ]
00007fa858000000  131072  131072  131072 rw---   [ anon ]
00007fa860000000  131072  131072  131072 rw---   [ anon ]
00007fa868000000  131072  131072  131072 rw---   [ anon ]
00007fa870000000  131072  131072  131072 rw---   [ anon ]
00007fa878000000  131072  131072  131072 rw---   [ anon ]
00007fa880000000  131072  131072  131072 rw---   [ anon ]
00007fa888000000  131072  131072  131072 rw---   [ anon ]
00007fa890000000  131072  131072  131072 rw---   [ anon ]
00007fa898000000  131072  131072  131072 rw---   [ anon ]
00007fa8a0000000  131072  131072  131072 rw---   [ anon ]
00007fa8a8000000  131072  131072  131072 rw---   [ anon ]
00007fa8b0000000  131072  131072  131072 rw---   [ anon ]
00007fa8b8000000  131072  131072  131072 rw---   [ anon ]
00007fa8c0000000  131072  131072  131072 rw---   [ anon ]
00007fa8c8000000  131072  131072  131072 rw---   [ anon ]
00007fa8d0000000  131072  131072  131072 rw---   [ anon ]
00007fa8d8000000  131072  131072  131072 rw---   [ anon ]
00007fa8e0000000  131072  131072  131072 rw---   [ anon ]

**Comment by yuvalp-k2view** [comment]
Fabric uses sqlite which is a native library.
It is possible for sqlite to consume and retain memory that is not managed by the JVM. The more sqlite instances, the higher the potential for data retention (as controlled by MDB_CONTEXT_POOL_SIZE).

We saw that some complex queries can affect this and consume a lot of memory.
Since 6.4, we also execute "PRAGMA shrink_memory" before returning the connection to pool.

A way to isolate this would be to work with a pool size of 0. This means that the sqlite context is discarded after each use
(available since fabric 6.4.0). This can have some performance implications when using large common databases.
In this mode, there is no limit to the number of concurrent Fabric Sessions.

Another thing to verify (to keep the answer general) is none-heap java managed buffers used by Cassandra and Kafka drivers. These are by default limited by -Xmx (so max managed memory can be twice the Xmx) or specifically by -XX:MaxDirectMemorySize.
