### ISSUE TITLE
how to determine NLS_DATE_FORMAT per all connections

### ISSUE THREAD

**Issue by tamarzohar** [k2view-academy/K2View-Academy#44]
Hi 
I want to manipulate date format in a session level for all the lu tables . how can I do it ? 

Thanks
Tamar

**Comment by lionbro1** [comment]
Hi,

You need to enhanced the DB type, use New Database Type from Template, in case of Oracle for example, and define the alter session command under Pool Properties, init SQL. save the new DB type.

Afterwards use TO_CHAR(field name) when running select statement from source interface in order to get the field in the defined structure.

Regards,
Lion
