### ISSUE TITLE
Does Fabric use "select 1 from dual" query for internal ops on Oracle interface?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#453]
Hi,
Does Fabric use "select 1 from dual" query anywhere internally in the product for Oracle interfaces? If so, where and can it be disabled/reduced? The DBAs have reported it as one of the top queries in the AWR reports.

**Comment by lionbro1** [comment]
Hi,

Yes, we use this query in order to validate the connection when establishing the first connect and when reusing connection from the pool.

It is defined on the DataBase Type. if you want to change it to a different query you need to define a new DataBase Type From Template, follow print screen as an example

![image](https://user-images.githubusercontent.com/21338328/155272711-bf432aeb-4386-48f3-b24c-bb6fbbe6ffc3.png)


and refer your Oracle interface to the new DB type that you defined.

More details can be found in the following article:

https://support.k2view.com/Academy_6.5/articles/05_DB_interfaces/10_database_types.html
