### ISSUE TITLE
Batch-Insert 

### ISSUE THREAD

**Issue by soniek123** [k2view-academy/K2View-Academy#493]
I have some doubts regarding Batch insert :-

1.We have batch option on dB command actor inside Broadway flow in the  k2view 6.5.3 version ,how to confirm batch insert is working or not?
2.We have any option to configured batch size?
3.How transaction rollback will behave if any exception occur middle of batch?

**Comment by natalylic** [comment]
The **batch** mode behavior of **db** actors is as follows:

> Data writing Actors can work in a batch mode. When the batch input argument is set to true, the Actor accumulates statements and performs them as a batch for better performance. It needs to be run in a transaction and the errors are reported as the batch is committed (every X record or on commit).

This is described in the following article: https://support.k2view.com/Academy/articles/19_Broadway/actors/05_db_actors.html

Regarding the batch size - it is not configured by the actor, but depends on your implementation and how you want to handle the transaction. 
The Transactions in Iterations are described here: https://support.k2view.com/Academy/articles/19_Broadway/23_transactions.html

**Comment by soniek123** [comment]
I gone through this article, but for example if I have 100 insert query how to confirm it is inserting as a batch not one by one. how to check in fabric.

**Comment by smokyMount** [comment]
Hi Nataly,

Does it mean then that the batch size will be equal to commit size?

For this example, will the batch size and commit size both be 5 if batch is set to true?
![image](https://user-images.githubusercontent.com/66338066/160861760-c897af10-5146-48be-85fb-85713c92dc2e.png)

**Comment by natalylic** [comment]
Hello! After additional research, I'd like to correct my previous answer regarding the batch size. 
The batch size of **db** actors is determined by the system parameter **IO_JDBC_BATCH_SIZE** which by default equals  **1,000**.  
In an example where the loop makes 5,000 iterations with one commit for all and batch is set to true, the actor will accumulate each 1,000 records and perform them as a batch, however there will be one commit after all 5,000 iterations. 
In the above example, where commit is defined to be every 5 rows, the batch and commit size are equal since commit size is less than batch size. 
To modify the default batch size, add the [io] section to the config.ini and set your required value of IO_JDBC_BATCH_SIZE.
To check that query is executed in a batch rather than one by one, run a trace with 'categories=database;operations=connection;'
In the trace file, you will see one SQL statement per batch (e.g. one INSERT) rather than SQL statement per each iteration (e.g. many INSERTs). Note that trace doesn't display SQL statements on fabric interface, but only of DB interfaces.
