### ISSUE TITLE
Get WS header inside WS code

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#589]
How can we get details of the WS headers from within the WS code?

**Comment by eyalk2** [comment]
May you try use custom payload

See here:
https://support.k2view.com/Academy/articles/15_web_services_and_graphit/05_edit_web_service_code.html

and examples here:
https://support.k2view.com/Academy/articles/15_web_services_and_graphit/06_web_services_code_examples.html#example-of-a-custom-payload---json

For headers, you can use this:
WebServiceUserCode.request().getHeader("<HEADER-NAME")
Or getHeaderNames,



From: dotants ***@***.***>
Sent: Thursday, July 7, 2022 3:20 PM
To: k2view-academy/K2View-Academy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [k2view-academy/K2View-Academy] Get WS header inside WS code (Issue #589)


How can we get details of the WS headers from within the WS code?

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk2view-academy%2FK2View-Academy%2Fissues%2F589&data=05%7C01%7Ceyal.orbach%40k2view.com%7C785c703406224c542d3a08da6012fe3c%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C637927931934556228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Db0jucLDEUnRusB6YAvt4bRXcPCFaZwWOUpRtmFai6o%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARWMWJF7DTZL3PIFRXSL2PDVS3DONANCNFSM525GH4TQ&data=05%7C01%7Ceyal.orbach%40k2view.com%7C785c703406224c542d3a08da6012fe3c%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C637927931934556228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FwOe2o%2BeH6hkJxxlPxkTysJ32hwKHM0yUT3Zt%2FSuc%2Bo%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>
* CAUTION: This email originated from outside of K2view *

**Comment by dotants** [comment]
Thanks
