### ISSUE TITLE
Reference table schema

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#597]
What is the actual impact (e.g. performance?) of setting different schema to reference tables, considering that they are build in SQLite, and since recent releases, built on distinct files? Thanks.

**Comment by lionbro1** [comment]
By default all reference tables are attached to one big sqlite file.

In order to get better performance (no dependancy on file locks) and scalability it is better to split the reference table to different schema by groups in such a way there is no locking dependency between the tables as they don't share the same sqlite file.

**Comment by feamcor** [comment]
Ok so the feature of splitting on different SQLite files is per schema, not per table. Thanks.

**Comment by lionbro1** [comment]
correct
