### ISSUE TITLE
How to use named params in SourceDbQuery actor of broadway

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#609]
Hello, 

Please see an example query that I want to run as part of broadway table population. 

Query - 
WITH Props AS
(
    SELECT *,
    ROW_NUMBER() OVER (ORDER BY PropertyID) AS RowNumber
    FROM Property
    WHERE PropertyType = ${PropertyType} 
)   
SELECT * FROM Props 
WHERE ID = ${ID}

I have added these parameters to the SourceDbQuery actor in BW and the query executes when using QB. But on executing a Get, the table population is empty since a blank input is passed to these arguments.   

Can you provide an example for BW for this scenario where we need a custom where clause ?

Regards,
Prathamesh

**Comment by natalylic** [comment]
The **SourceDbQuery** actor in the population flow generates a WHERE clause using the expression passed to it using the **parent_rows** argument which is passed from the **PopulationArgs** actor. The query that you have built is maybe valid in the QB, but did you run your population flow in Debug mode to check what is passed in the parent_rows argument? Probably because you're not using a standard query, you should replace the **SourceDbQuery** actor by the **DbCommand** actor.

**Comment by natalylic** [comment]
https://support.k2view.com/Academy/articles/07_table_population/14_table_population_based_Broadway.html
