### ISSUE TITLE
Is response from Fabric cache or web cache

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#623]
Hello,

This is a continuation to issue #602 regarding cache hit.
On progressing  further in the project, we think there are 2 caches involved , the fabric mdb cache ( answered in 602 ) and the web server's response cache. Web cache means that for repeated requests, the response is received from the web  response cache rather than going to the server mdb cache.  
Example - Repeated calls are invoked for a web service with same inputs, the response is sometimes from the response cache vs the mdb cache.

Do we have any metrics for such a scenario which determines if the request was served through the response cache? 

A similar topic https://stackoverflow.com/questions/13140318/check-whether-network-response-is-coming-from-server-or-chrome-cache

Regards,
Prathamesh

**Comment by yuvalp-k2view** [comment]
Are you using the ResultCacheFilter or some other Filter? If not, the response is always live from the API.
The JMX counters can be used to know if you hit the cache or Storage.
The Filters do not have JMX counters. You can know the filter is used since no JMX counter will be incremented (including web service stats).
