### ISSUE TITLE
KMS related questions

### ISSUE THREAD

**Issue by prathameshpalaskark2view** [k2view-academy/K2View-Academy#650]
Hello,

After integrating AWS KMS based on Fabric 6.5.9 , just a couple of questions. 
1> How to verify that the fabric is indeed using the new KMS ? 
2> Is there any command like deactivatekey to deactivate key similar to activatekey  ? 

Regards,
Prathamesh

**Comment by prathameshpalaskark2view** [comment]
Second part of the question was answered by Eyal during a short call . To deactivate, delete the key from the k2auth keyspace. Hence, only the first part of the question remains to be answered.

**Comment by eyalk2** [comment]
1.  How to verify that the fabric is indeed using the new KMS ?
A:Once you run it with appropriate parameters and got prompt action succeeded it is quite enough. There is option to dig in and look at Cassandra at k2auth.keys_descriptions table. There, keys exist with their creation timestamp. The latest is the active. Look for key generator and key store fields to verify it is KMS

  1.  Is there any command like deactivatekey to deactivate key similar to activatekey ?
A: To deactivate a previous key, like KMS or any other, you shall create new master key, using the activatekey. To get back to internal master key - run this command without parameters (as its default is the internal).

Note: Fabric still needs to be able to connect to KMS master key in case it was active, so that it will be able to decrypt data which was encrypted with previous key which used KMS.
This means that you shall not delete this information from config.ini and also need a connection to KMS. When Fabric node is coming up, it checks that table and try to connect to KMS, in case it exists in table, even if current master key is not KMS. If it cannot connect - node will not able to come up.

This is also explained at these 2 articles:
https://support.k2view.com/Academy/articles/26_fabric_security/02_fabric_entities_design.html
and
https://support.k2view.com/Academy/articles/99_fabric_infras/devops/10a_fabric_master_key_integrated_with_kms.html
