### ISSUE TITLE
How does "Required Reference Tables" property work for reference tables?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#660]
Hi,

My understanding of this property is that Fabric should sync the required tables before starting the sync of the table that has dependency on them.
I tried to test it by creating 3 tables - A, B and C, where table C "requires" tables A and B. When I run ref_sync tables='ALL', it triggers sync for table C before A and B have finished syncing. Shouldn't it wait for tables A and B to finish syncing before it starts syncing itself?

Attaching export for reference.
[requried_references.zip](https://github.com/k2view-academy/K2View-Academy/files/9749613/requried_references.zip)

**Comment by k2viewLTD** [comment]
See picture

[Image.png]




[Icon  Description automatically generated]

Achi Rotem

CEO

Mobile: +972-50-847-8470



________________________________
From: Hardik Parekh ***@***.***>
Sent: Monday, October 10, 2022 5:38:02 PM
To: k2view-academy/K2View-Academy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [k2view-academy/K2View-Academy] How does "Required Reference Tables" property work for reference tables? (Issue #660)


Hi,

My understanding of this property is that Fabric should sync the required tables before starting the sync of the table that has dependency on them.
I tried to test it by creating 3 tables - A, B and C, where table C "requires" tables A and B. When I run ref_sync tables='ALL', it triggers sync for table C before A and B have finished syncing. Shouldn't it wait for tables A and B to finish syncing before it starts syncing itself?

Attaching export for reference.
requried_references.zip<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk2view-academy%2FK2View-Academy%2Ffiles%2F9749613%2Frequried_references.zip&data=05%7C01%7Cachi%40k2view.com%7C8da85b5e8e6d43a53fd908daab1017e0%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638010384818210693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wCIx%2BZQ8aYr%2FnaHzEZP3XbA4GE3NjcL6cq011fgqM0g%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk2view-academy%2FK2View-Academy%2Fissues%2F660&data=05%7C01%7Cachi%40k2view.com%7C8da85b5e8e6d43a53fd908daab1017e0%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638010384818210693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7eG8egXrNw25skCspQmu%2FHBeSa7aVqNXG7TyzNvyuTI%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADMJN7BBYHJQ2CDKHEE3KBTWCSLEVANCNFSM6AAAAAARBXLC3U&data=05%7C01%7Cachi%40k2view.com%7C8da85b5e8e6d43a53fd908daab1017e0%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638010384818210693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=berq28QTKliBh%2BX11IIGXhmCUBgqSi0M2AFtfAZzn%2Bg%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

* CAUTION: This email originated from outside of K2view *

**Comment by lionbro1** [comment]
it should not sync table C before A and B were fully synced, I will ask QA team to test it again, but if you face such an issue please open a freshdesk call with all the details.

**Comment by lionbro1** [comment]
it was recorded as defect that will be release on 6.5.9 HF2 and fabric 7
