### ISSUE TITLE
How are Subscribe and SubscribeBatch actors different?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#669]
Hi,

All the input parameters, including the batch ones, for the Subscribe and SubscribeBatch actors are the same. How are these actors different? If the values for batch parameters are same for both actors do they behave the same?

I understand that based on the article below that SubscribeBatch is supposed to read in batches while Subscribe does not. Why do we have batch params on the Subscribe actor as well?
https://support.k2view.com/Academy/articles/19_Broadway/actors/04_queue_actors.html

**Comment by natalylic** [comment]
Both can read messages in batches. The difference is in the actor's output. The **Subscribe** actor iterates on the messages returning them one-by-one while the **SubscribeBatch** returns the whole batch and then you can iterate on it in your flow.
The **SubscribeBatch** actor is useful when a transaction is needed and you want to control when commit is performed (on the batch completion). In case of **Subscribe** actor, since it always returns one row - you don't know when one batch is finished and another one starts. 
I will clarify it in the article.
