### ISSUE TITLE
Use of ODBC driver instead of JDBC

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#684]
Hi Product team,
Using latest Fabric (6.5.9),
is it possible to connect to a database (e.g. Oracle RDB) using its ODBC driver instead of JDBC?
Does Fabric (that runs on Linux), include any ODBC-JDBC bridge?
Or would it require some 3rd-party one?
If so, any recommended bridge from previous experience?
Thanks.

**Comment by k2viewLTD** [comment]
There is a JDBC driver for Oracle RDB.
I don’t remember in which project we are using it but I’m sure we have connected in the past.





[Icon  Description automatically generated]

Achi Rotem

CEO

Mobile: +972-50-847-8470



________________________________
From: Fábio Corrêa ***@***.***>
Sent: Monday, November 28, 2022 9:35:06 PM
To: k2view-academy/K2View-Academy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [k2view-academy/K2View-Academy] Use of ODBC driver instead of JDBC (Issue #684)


Hi Product team,
Using latest Fabric (6.5.9),
is it possible to connect to a database (e.g. Oracle RDB) using its ODBC driver instead of JDBC?
Does Fabric (that runs on Linux), include any ODBC-JDBC bridge?
Or would it require some 3rd-party one?
If so, any recommended bridge from previous experience?
Thanks.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk2view-academy%2FK2View-Academy%2Fissues%2F684&data=05%7C01%7Cachi%40k2view.com%7C8ce47f55bca348413d7a08dad177a82e%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638052609100679296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=21D0C7lIy3uQoCBI0RTPCsl8IhwFw0dXKs0m3ib1my0%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADMJN7ET6VMULGZZRLUG2B3WKUCOVANCNFSM6AAAAAASNV73U4&data=05%7C01%7Cachi%40k2view.com%7C8ce47f55bca348413d7a08dad177a82e%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638052609100835524%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uL5Rw70Pufavn8sDhwO5a1OLxgEcqEb7buyb1W2jM5c%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

* CAUTION: This email originated from outside of K2view *

**Comment by lionbro1** [comment]
You can use only jdbc drivers in fabric. we don't have any odbc-jdbc bridge in fabric
