### ISSUE TITLE
possible to run batch or migrate using a query from another LU Type?

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#708]
With batch commands, we can generate the IIDs using a query against a db interface with the form "batch LUTYPE from <dbInterface> using <query>"...

However, can we also use a query against a different fabric LU instance?  E.g. PARENT LU Type has a table "some_table" with a field containing child_id and many rows; I want to batch / migrate a different LUType of CHILD LU for every child_id instance in PARENT.some_table. But if I try to run "batch CHILD from fabric using ('select child_id from PARENT.some_table')..." I get an exception.  I've tried using an external fabric interface, but then the PARENT lu is not in context (also tested setting AUTO_MDB_SCOPE and passing the PARENT IID as a "where" condition).

Is it possible to have a batch or migrate generate IIDs from a query against another lu instance?

**Comment by natalylic** [comment]
You can migrate the instances of CHILD LU based on the list of instances of PARENT LU using the following command:
```BATCH PARENT from fabric fabric_command='sync_instance CHILD.?';```
Your command above is problematic because you use the SQL statement on Fabric which is ambiguous since it depends on what is currently attached to the Fabric scope. Besides you run "BATCH CHILD" instead of "BATCH PARENT".
The last question that you asked - _Is it possible to have a batch or migrate generate IIDs from a query against another lu instance?_ - is confusing. Did you mean - against another LU type's instances? Anyway I hope my above explanation answered your question. If not - please open a ticket, including the exception you're getting, so that we will be able to investigate it.
