### ISSUE TITLE
Fabric versions when several Fabric clusters are on one Cassandra cluster

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#725]
If I have multiple fabric clusters (projects) on top of a single Cassandra cluster, does fabric need to be on same version for each project?
Example - I have 3 fabric clusters, F1, F2 and F3, on a single Cassandra cluster. Can I have F1 and F2 on v6.5.5 and F3 on v6.5.9 or higher?

**Comment by eyalk2** [comment]
Fabric stores separated keyspaces per project.
If you wish same project to work on different clusters, for example running different fabric versions, you shall set different cluster_id at config. Then, you will have different KS per cluster-id.

From: Hardik Parekh ***@***.***>
Sent: Sunday, January 22, 2023 1:46 AM
To: k2view-academy/K2View-Academy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [k2view-academy/K2View-Academy] Fabric versions when several Fabric clusters are on one Cassandra cluster (Issue #725)


If I have multiple fabric clusters (projects) on top of a single Cassandra cluster, does fabric need to be on same version for each project?
Example - I have 3 fabric clusters, F1, F2 and F3, on a single Cassandra cluster. Can I have F1 and F2 on v6.5.5 and F3 on v6.5.9 or higher?

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk2view-academy%2FK2View-Academy%2Fissues%2F725&data=05%7C01%7Ceyal.orbach%40k2view.com%7Ce44e6b3e8b504047640508dafc09aa74%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638099415689388218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=e7GDkuBLNjz2PflyTPM50l5b7db%2B6vANziFilK3kY90%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARWMWJBCHOZHPBJPYJDCS6DWTRYL5ANCNFSM6AAAAAAUCU6B74&data=05%7C01%7Ceyal.orbach%40k2view.com%7Ce44e6b3e8b504047640508dafc09aa74%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638099415689388218%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YFiaVW0SUwrvl2iaTpfuCMn5psQhfRj7l2BwM%2FHJsV0%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>
* CAUTION: This email originated from outside of K2view *

**Comment by smokyMount** [comment]
Hi,
In my case it is a different project in each fabric cluster but the underlying Cassandra is common for all. We do use cluster_id to differentiate between keyspaces from different projects.
I just want to confirm if it is ok to have different versions of Fabric for each of these projects.

**Comment by eyalk2** [comment]
True, no problem.
Be aware that per Fabric release we describe with which Cassandra version it works. As long as these Fabric version you run are aligned with - it is OK
