### ISSUE TITLE
How to split the Fabric cluster into two independent clusters.

### ISSUE THREAD

**Issue by aniruddha789** [k2view-academy/K2View-Academy#774]
Fabric 6.5.9

Hi, I currently have two nodes in one fabric cluster. I want them to be independent and in their own cluster. How do I go about it and is there any documentation already available for this. By the way earlier they were independent nodes in different clusters. I observed they became nodes in same cluster when I upgraded from Fabric 6.5.5 to 6.5.9.

**Comment by lionbro1** [comment]
Hi,

Do you want to use the same Cassandra for these 2 Fabric clusters, if so, please follow this article on how to use the cluster_id in node.id file, https://support.k2view.com/Academy/articles/02_fabric_architecture/05_fabric_main_configuration_files.html

You need to make sure HOSTS parameter is pointing to the correct IPs.

Upgrade from 6..5 to 6.5.9 should not trigger clusters split, it might be due to manual changes on the config.ini file.
