### ISSUE TITLE
Trigger UPDATE

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#799]
Fabric 6.5.9

There is a trigger function that is being used in a data pipeline use case to determine if a row was changed and stamp some control info into a control table within the LUI.

The relevant tables are defined with Delete Mode `NonUpdated` and their population flows with DbLoad command `upsert`.

Will trigger function be called when no actual changes were performed to an existing row?
Or would it still be called and to determine if changes were performed I should use `changedFiles()`?

Please advise.
Thanks.

**Comment by natalylic** [comment]
The **NonUpdated** Delete Mode on the LU table means deletes previous records (created by the earlier sync) where data no longer exists for the LUI in the source.
If the Delete Mode is **NonUpdated**, it is recommended to define a PK on the LU table and set the LU table population mode to **Upsert** or **Update** in order to delete only the old data. If the LU table does not have a PK, new records are added to the LU table and all previous records are deleted.
The **Trigger** function will run for any change done on the sqlite file, even if updated to the same value as the origin.
