### ISSUE TITLE
calling WS without format as input fails

### ISSUE THREAD

**Issue by tarikh03** [k2view-academy/K2View-Academy#80]
PASS -> http://localhost:3213/api/testWS?token=ttoken&format=json

FAIL -> http://localhost:3213/api/testWS?token=ttoken

is it possible to set default format so when format is not available as input it could take the default one?

it fails on webserver level and doesnt reach fabric.
~/k2view/webserver/webapps/admin/gui/script/helenos.js

error message is:

"Unsupported media type text/html,application/xhtml+xml,application/xml;q\u003d0.9,image/webp,image/apng,*/*;q\u003d0.8,application/signed-exchange;v\u003db3;q\u003d0.9"

version: 6.1.2_7

**Comment by lionbro1** [comment]
Hi,

The json format is defined as a default, there is no need to add it as a part of the URL, you can see this behavior in postman for example.
However, when using internet explorer or chrome, it defines a different format on the header request, a format that is not supported by Fabric, that's the reason it is a must to define the format, in order to override this format.
