### ISSUE TITLE
Batch Java API

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#803]
Fabric 6.5.9

What is the Java class to be used for creating and inspecting a batch details and its entities details programatically instead of using Fabric SQL?

Please advise.
Thanks.

**Comment by lionbro1** [comment]
Our recommended approach is to use the commands.

Why you look for APIs? What is missing in the command?

‫ב-27 במרץ 2023, בשעה 19:36, ‏‏Fábio Corrêa ***@***.***> כתב/ה:‬

﻿

Fabric 6.5.9

What is the Java class to be used for creating and inspecting a batch details and its entities details programatically instead of using Fabric SQL?

Please advise.
Thanks.

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fk2view-academy%2FK2View-Academy%2Fissues%2F803&data=05%7C01%7Clion.brotzky%40k2view.com%7Cce7095fb4efe48a9c1db08db2ee16d94%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638155317968215230%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xVUuC61vNjc5iX4UnoWZehTNh1%2FKhL7tha8zyQhNAbU%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFCZRWEWLCB67X5Z5M6XBUTW6G6ZDANCNFSM6AAAAAAWJMFXMU&data=05%7C01%7Clion.brotzky%40k2view.com%7Cce7095fb4efe48a9c1db08db2ee16d94%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C638155317968215230%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yb045ErfvBzTBne6%2Foug1BL1nH%2BaE%2BVijY81yaVhvWE%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

* CAUTION: This email originated from outside of K2view *
