### ISSUE TITLE
Migration to Object Storage (AWS S3)

### ISSUE THREAD

**Issue by feamcor** [k2view-academy/K2View-Academy#855]
Fabric 6.5.9

When an LU `Storage` is changed to, for instance, `S3`..  
1. Will Fabric migrate the LUIs on-the-fly upon the first `get` after deployment?
2. If so, will it migrate when sync mode is `on` or `force`? Or also on `off`?
3. When an LUI is migrated, will the blob in `entity` and `entity_chunks` (if there) be deleted?
4. What is the recommended approach? Leave the migration to happen organically or force a massive migration using a batch?
5. How to check on `entity` what LUIs were already migrated, or not?

Please advise.
Thanks.

**Comment by lionbro1** [comment]
Hi,


Since Fabric 6.5.7 a new storage type was created that can be used to move data from storage A to  
storage B (e.g. Cassandra to S3) gradually with no system downtime or heavy resync processes. 
The following configuration was added in config.ini file under the fabricdb section: 
MDB_DEFAULT_SCHEMA_CACHE_STORAGE_TYPE=TRANSITION 
STORAGE_TRANSITION_FROM=CASSANDRA 
STORAGE_TRANSITION_TO=S3 
When trying to bring data from a Fabric microDB, Fabric first checks (ie, reads)   STORAGE_TRANSITION_TO for data. If Fabric cannot find data there, it then reads STORAGE_TRANSITION_FROM for data.  
On save, Fabric saves data in STORAGE_TRANSITION_TO. If the microDB was found in STORAGE_TRANSITION_FROM during the read process, then after saving the data in STORAGE_TRANSITION_TO, Fabric deletes the data that was found in STORAGE_TRANSITION_FROM.  
If  STORAGE_TRANSITION_FROM is set to blank, the system will stop reading STORAGE_TRANSITION_FROM (no need for restart).

**Comment by feamcor** [comment]
Thanks for your reply.

I then assume that transition is a global setting apart from the Storage setting on Schema.

What if S3 is not set as global default on config.ini and the transition would be done per LU?

Is there the option Transition on Studio?

When it would be known that the transition is completed and the settings could be changed to, for instance, S3?

Please advise.
Thanks.

**Comment by lionbro1** [comment]
You can't define it on the LU schema in Studio. It is controlled only on config.ini level.

However, if there are some LUs that are not part of the transition, you can define the storage in the LU schema for them with a value that is different then the default.

There is no indication that transition is done, you can control it proactively scheduling nightly batch runs to transition all instances to the new storage.

**Comment by feamcor** [comment]
So, my last questions are...
- How to check on the `entity` table that an LUI was migrated? Would the BLOB be empty/null?
- Is the (S3) object ID being stored somewhere, or is it composed dynamically?
- Or is there any flag (apart from the settings in config.ini) explicitly indicating that the LUI is in object storage?

Please advise.
Thanks.

**Comment by lionbro1** [comment]
* The instance is deleted from entity table.
* It is not one to one mapping, each character on the iid is mapped to a character that is valid on the target platform (for example S3).
* The Flag is on the LU schema level not LUI

**Comment by feamcor** [comment]
_"The instance is deleted from entity table"_
So does it mean that there will be no row in `entity` table anymore?
If so, how does Fabric know what are the LUIs that were loaded so far?
How would, for instance, a batch based on Fabric, or a CDC republish, know the current set of LUIs?
Please advise.
Thanks.

**Comment by lionbro1** [comment]
Hi,

Yes the instance is deleted from entity table. If you are in a transition period and you defined the config.ini this way, for each instance in the LU if the storage is defined as default, 

  Fabric first checks (ie, reads) STORAGE_TRANSITION_TO for data. If Fabric cannot find data there, it then reads STORAGE_TRANSITION_FROM for data.
  On save, Fabric saves data in STORAGE_TRANSITION_TO. If the microDB was found in STORAGE_TRANSITION_FROM during the read process, then after saving the data in STORAGE_TRANSITION_TO, Fabric deletes the data that was found in STORAGE_TRANSITION_FROM.

else Fabric will consider the storage defined in the LU schema, for example if it's defined as Azure BLOB store, it will go to Azure BLOB store all the time without considering if there is old data in Cassandra.

Furthermore, to delete instance without running the delete instance command while you don't know where the instance is stored (e.g. S3, Cassandra, etc..) you can use the following API getConnection("fabric").unwrap(FabricDbConnection.class).erase(schema, iid)

**Comment by feamcor** [comment]
- Can TRANSITION handle reversals? I mean, for instance, from S3 to CASSANDRA?
- Considering a CASSANDRA to S3 transition scenario, what are the guarantees that entity row won't be deleted prior to confirmation that BLOB was successfully stored in S3?
- Do you have any estimation of the overhead upon get added by the transition flow?
- Is there any mechanism to (at least) delay entity row deletion in Cassandra? I mean, on the unlikely event of failure on storing on S3 and transition should be reverted/stopped.

Please advise.
Thanks.

**Comment by lionbro1** [comment]
1 - yes, any storage to any storage can be transitioned. 
2 -there is no delete before write confirmation. 
3 - the main overhead is the search for the iid in the new device prior to finding it in the old one. A more minor point is that delete-instance has to try and delete on both. 
4 - there isn’t. We could remove delete completely with a small patch and you could batch delete later by querying s3 for the list. Not sure it’s worth the pain since s3 is highly dependable (multi az).

**Comment by feamcor** [comment]
@lionbro1, on the `config.ini/s3_storage` I see the following comment above the `BUCKET_NAME` attribute.

```ini
# Optional. If presented, use one bucket for all lu's
#BUCKET_NAME=
```

Please elaborate on the meaning of "Optional".

If no bucket name is provided, where would Fabric store the objects?
Would it try to create a bucket?
Or would it expect section be LUT (see below)?

The comment also gives the understanding that each LU could be stored on different buckets.
If so, how would that be configurable?
Would it be by introducing new sections like `[s3_storage.<LUT>]`?

Please advise.
Thanks.

**Comment by lionbro1** [comment]
If bucket name is not provided fabric will try to create a bucket for each LU, but this is not the recommended as the bucket name will be shared between all cloud users, it means the bucket name might be already in use in this region, this is why we strongly recommend to populate the  bucket name in the config.ini.
