### ISSUE TITLE
limitation on DbCommand actor.

### ISSUE THREAD

**Issue by MohamedSaleh295** [k2view-academy/K2View-Academy#866]
I have a flow that using DbCommand (return about 2M records) , this DbCommand connected to csvBuilder and the csvBuilder is connected to fileWrite. 
is there any limitation on the number of records on DbCommand or fileWrite ?

**Comment by natalylic** [comment]
**DbCommand** actor has no limitation on the number of records, because it returns a result set (virtual array) containing the rows. The results are not uploaded to the memory. You can iterate on the result set until it's empty:
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/0e6f514c-9758-40a7-a450-3325ac6a9246)
Note that since you have a large number of records returned by the DbCommand actor, you can optimize your flow as follows:
* split the results of DbCommand by building an array (e.g. size of 1,000 rows)
* build the csv format from this array
* write the whole thing into file
* reset the array and do it all over
* the last step is to build csv and write into file the remaining part
The flow will look like this:
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/58ab6254-5bec-4f5d-823d-1a637a43dc83)
