### ISSUE TITLE
Is it recommended to move files from on server to another using Broadway flows?

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#875]
Hi,
There is a requirement to move files from one node to another. Since Broadway is used for orchestration, can we move the files using an Exec or an LuFunction actor?

**Comment by natalylic** [comment]
There are various ways to move the files, depending on what is the purpose of this action.
Please describe your use case and we will provide you a specific recommendation.

**Comment by smokyMount** [comment]
For this use case, we will receive over 100 huge files on one server. We use Broadway flows for orchestration and need to distribute the files to other servers for parallel processing (which is done by another application).

**Comment by natalylic** [comment]
It is still not clear from your answer, whether Fabric is supposed to perform any transformation of these files, while moving them from one server to another. If yes, definitely you should use Broadway flow and existing actors.
If not, there is no reason for Fabric to be involved into this activity because it will only provide an additional load on Fabric server, without any added value.
