### ISSUE TITLE
TDM on AWS Keyspaces - Enable TTL for tables

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#879]
TDM utilizing  AWS Keyspaces. The default state of the tables is not to allow TTL
For which tables in Keyspaces it is required to alter to enable TTL functionality?

**Comment by tahata1** [comment]
Hi
In TDM we are using k2masking keyspace and entity_list tables in Cassandra/Keyspaces.

You need to alter the TTL for k2masking keyspaces and all <lu name>_entity_list tables under k2view_tdm Keyspace.

In case you still have other root LUs that still do not have an equivalent entiy_list table, I suggest you change the flow createLuExternalEntityListTable to use DBCommand instead of actor DBCassandraCreateTable and use the following SQL statement to enable the TTL:

	CREATE TABLE ${luName}_entity_list (
		lu_name TEXT,
		source_env_name TEXT,
		source_iid TEXT,
		tdm_eid TEXT,
		task_execution_id TEXT,
		PRIMARY KEY(task_execution_id,lu_name,tdm_eid)
	)  WITH default_time_to_live = ${TTL}


Where luName and TTL are inputs to that DBCommand
