### ISSUE TITLE
Proxy settings for calling external WS from Fabric

### ISSUE THREAD

**Issue by dotants** [k2view-academy/K2View-Academy#901]
Hi

How can I set "proxy" for WS calll from Fabric to external WSs?
[for both Linux and Windows]

**Comment by eyalk2** [comment]
what do you mean by "proxy"?

**Comment by dotants** [comment]
I meant that all calls to external WSs must be done using proxy that will route the calls

**Comment by eyalk2** [comment]
what is this proxy? why should Fabric care about? if you set the call from Fabric to go to this proxy as endpoint, then it is transparent.
you might need to probably define some parameters, so that proxy will know where to move.
Without more details or requirements, it is hard to know if there is any challenge.

________________________________

**Comment by dotants** [comment]
So - how to set the proxy for all Ws calls on a machine?
[Linux and Windows]

**Comment by eyalk2** [comment]
as we spoke, proxy in machine level shall be done using the OS commands, not at Fabric. 
For example, at Linux set the environment variables https_proxy and https_proxy. (and to make it persistent you shall define the environment variables file)

**Comment by dotants** [comment]
The Windows proxy settings are for browsers only and are not used by Fabric Studio / debug instance...
Is there a way to configure Fabric Studio to use the proxy settings?
