### ISSUE TITLE
Broadway configurations for optimal performance

### ISSUE THREAD

**Issue by smokyMount** [k2view-academy/K2View-Academy#916]
Hi,

Are there any config parameters we can tweak to optimize the performance when there are hundreds of Broadway flows running at any given time from batch?
What does following parameters do - BROADWAY_LU_POOL_SIZE?

**Comment by eyalk2** [comment]
is this the same BW flows that shall run over and over?
as you can see here, in another Q&A you opened - https://github.com/k2view-academy/K2View-Academy/issues/316 - 
It can help for performance in such case of re-use - because the compiled BW is there (i.e. in that number of instances as in the config)
