### ISSUE TITLE
Can a TDM post-execution task recieve input parameters (specifically, reference the entities included in the TDM task)?

### ISSUE THREAD

**Issue by JohnH-K2View** [k2view-academy/K2View-Academy#931]
description only says a baatch commaand will be called against the post-execution task; but not if it can recieve input. Is there a apre-defined input (similar to interface listener) so the post-execution task can be aware of the task details & handle accordingly?

**Comment by taliei** [comment]
Hi.

The post-execution process cannot get external parameters from the task window. However, it can get the task details from the TDM DB table based on the task execution ID: it can get the value of the TDM_TASK_EXE_ID Global or get the value of the taskExecutionID external input parameter in order to have the task execution ID of the current execution and select the required data from the TDM DB tables accordingly. 

Regards,
Tali
