### ISSUE TITLE
TDM - Masking instance_id field 

### ISSUE THREAD

**Issue by AlexMaziya** [k2view-academy/K2View-Academy#939]
Assuming I am masking the CUSTOMER.SSN which is a PII field and acts as the ROOT_COLUMN_NAME for my LU.
What would be the best TDM approach to anonymize this field value from ALL TDMDB tables/views + Cassandra tables in the TDM execution process.

**Comment by taliei** [comment]
In generate, it is recommended to use non-sensitive fields as linked fields between the LU tables since the masking is typically done in the LU population, and if you mask the SSN in the Customer table for example, you cannot use it to link child tables to customer tables in the LU schema. Note that from TDM 8.1, the TDM is integrated with Fabric catalog masking where the catalog masks the PII values in the LU population.

If you need to use a PII field to link LU tables, you need to avoid masking this field in the LU population and mask it after populating the LU tables by adding a masking flow that runs after all LU tables' populations (set the execution order with a higher value).

You can use a Masking actor that invokes the related data generator, for example - RandomSSN Actor, to mask the PII field and set its parameters to keep the consistency of the field within the root instance id, environment id, and task execution id. 


For more information see - 
https://support.k2view.com/Academy/articles/TDM/tdm_implementation/11_tdm_implementation_using_generic_flows.html 

https://support.k2view.com/Academy/articles/39_fabric_catalog/11_catalog_masking.html
