### ISSUE TITLE
Is there a way to add condition into 'else' stage to be like 'else if'?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#948]
Hello, I have a BW flow and I need to analyze result from Stage X, Actor Y and split my 'next' logic on 3 branches based on result. 

I can add stage after with stage condition and check if result = value_1... then I can split and do 'else' stage, but it looks like I can not add it like 'else if' to compare against value_2 and then add another one 'esle if' for value_3. So I have to add 'next' stage after 'else' and introduce condition there and then the same for another 'else'.

My goal to have all 3 'conditions' covered by the same stage with split on 3 or 4 branches to avoid extra 'empty' stages - is there a way to achieve it?

______________
Best regards,
         Andrey

**Comment by natalylic** [comment]
Hi, as shown in the Example _conditions.flow_, you can split and set a condition on each branch.
This is not equivalent to 'else if' because both conditions are evaluated - _Concat1_ and _Equals1_ in the below example. So, if both Concat1 and Equals1 are true, both branches will be executed. If however you build the condition in a way that only one of them can be true, only one branch will be executed. _Else_ is executed only if non of the conditions is true.

![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/ce02981e-2d6c-4437-9fcb-4b9cf117dac0)

**Comment by avvakandr** [comment]
Hi Nataly, I understand thank you! I actually was trying to avoid this approach with 'else-if' branching instead of 'if', since if my first 'condition' is met - I'm still going to verify all other branches conditions irrespectively... 

______________
Best regards,
          Andrey

**Comment by natalylic** [comment]
Correct, all conditions will be checked. 
The other option is as you already know, to split it to if / else and then additional conditions, something like this:
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/d274518e-61dc-4f39-a78a-a444490a1b44)
