### ISSUE TITLE
How to reset 'outputs' from InnerFlow execution 'n-1' in case of inner flow error on execution 'n' ?

### ISSUE THREAD

**Issue by avvakandr** [k2view-academy/K2View-Academy#955]
Hello - I have an issue with iterations and error handling for inner BW flow: 

I created a simple BW flow just to replicate my issue - and this flow iterates from 1 to 2 and calls for inner flow supplying 'iteration' number as input and expecting 'result'. I also have ErrorHandler actor on the same stage with my Inner Flow actor.

Inner flow returns "OK" for the first iteration, and throws an error (using Fail actor) for the second iteration.

I would expect that for second iteration (when I throw error) my result value will be reset to null , but in fact my next actor still see result as 'OK' or whatever previous execution returned... I tried to use reset actors for inner flow and next actor (logger in this case), but nothing works.

Is there anything I can do to reset previous execution result?

Main Flow:

<img width="482" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/0ac3e5d5-453e-439a-8ff2-8eec9ac75f0b">

Inner Flow:

<img width="518" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/2d16a5d3-22b7-4593-b4b8-9ae5f8b8a02b">

____________
Best regards,
         Andrey

**Comment by natalylic** [comment]
Hi Andrey,
Each actor keeps the output of its last successful execution. In your example, the **Const2** actor is not executed in the 2nd iteration because the flow fails before it reaches this actor. As a result, the **InnerFlow1** output remains OK (from the 1st iteration).
The question is - what exactly are you trying to do in your flow?
If you need to use the **InnerFlow1** output only if there was no error in the previous stage, you can add the stage condition to **Stage 4** checking the error handler result. Or you might modify the inner flow to clear the output in case of error. 
I have a short guide on using actor's output in case of Split Iteration - see [here](https://support.k2view.com/Academy/articles/19_Broadway/21b_iterations_with_condition.html#using-outputs-of-actors-in-split-iteration) and let me know if you have additional issues or concerns.

**Comment by avvakandr** [comment]
Hi Nataly - in my flow I actually have condition stage after innerflow to analyze the outcome and this is where it doesn't work in case of error, since output is still carrying the value from previous execution. Based on your recommendation I can add one more condition to check ErrorHandler result.

You mentioned I can clear output from innerflow - I was trying to reset it to 'reset' value in the first stage of my inner flow, but in case of error this doesn't seem working and I'm still getting 'OK'. How can I do this?

<img width="244" alt="image" src="https://github.com/k2view-academy/K2View-Academy/assets/92332494/1273d972-58b9-46b8-a8d7-a7cabbf2ca93">

____________
Best regards,
         Andrey

**Comment by natalylic** [comment]
Sorry my mistake - you can't impact the InnerFlow's output by clearing the value inside the inner flow...
You can add the condition to check the ErrorHandler result and then add another condition on the InnerFlow output as below:
![image](https://github.com/k2view-academy/K2View-Academy/assets/62207927/f9db05fc-7b9f-4b03-ab23-0a13d841f398)


This is of course only relevant when the error in the ErrorHandler is suppressed. I guess this is what you're doing, otherwise the flow would end after the exception and not continue to the next stage.

**Comment by avvakandr** [comment]
Hi Nataly - ok, understood. And yes, I'm doing suppress for error handler...  wanted to 'save' w/o extra stages, but seems not this time :)

Tested as you suggested, and it is working... Thank you!

____________
Best regards,
         Andrey
