### ISSUE TITLE
Broadway output while using Broadway_job

### ISSUE THREAD

**Issue by rhcp20004** [k2view-academy/K2View-Academy#987]
Hi,

I'm trying to stop the Broadway flow, and the only option available is to run PS command and kill the process.
I also tried to use Broadway_job command instead but I am facing an issue to get the Broadway output since its a job and the output is the details of the job.

I'm expecting to get the result output from the Broadway flow while using k2api.

Command : Broadway lu_name.flow_name ....
Broadway result : 
Please see below Broadway result img
<img width="576" alt="broadway result" src="https://github.com/k2view-academy/K2View-Academy/assets/76520630/69dd849d-df64-4067-bdcf-f02f8ce5166b">

Command : startjob BROADWAY_JOB name.....
Broadway_job result : 
Please see below Broadway_job result img
<img width="660" alt="broadway_job result" src="https://github.com/k2view-academy/K2View-Academy/assets/76520630/4a9ea6a6-cbdd-4eb7-9a4a-faaf822eae45">

- How can I control the Broadway in order to stop or pause the process?
- I can control the Broadway while using the Broadway_job, but how can I get the Broadway output parameters?

**Comment by natalylic** [comment]
Please provide more information as the context of your questions is not so clear.
* What is the reason for stopping or pausing the Broadway flow in the middle? The flow can be stopped at a certain step (stage) by setting a [stage condition](https://support.k2view.com/Academy/articles/19_Broadway/19_broadway_flow_stages.html#what-is-a-stage-condition). If the condition returns true, continue the flow, otherwise stop it.
* The Jobs mechanism passes the job through a series of [statuses](https://support.k2view.com/Academy/articles/20_jobs_and_batch_services/02_jobs_flow_and_status.html). Once you run the STARTJOB command, the job might be first in the waiting status, as it is waiting to get started. The STOPJOB command is not immediate, since the job might be in the middle of some task. 
* The Broadway flow output parameters are returned by the flow upon its completion. They need to be defined as [External](https://support.k2view.com/Academy/articles/19_Broadway/03_broadway_actor_window.html).

**Comment by lionbro1** [comment]
@rhcp20004 please comment back with the details otherwise we will have to delete this Q&A
